version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog_app
      MYSQL_USER: blog_app
      MYSQL_PASSWORD: password
    ports:
      - "3377:3376"

  redis:
   image: "redis:4.0-alpine"
   command: redis-server
   ports:
      - "6380:6380"
   volumes:
      - redis:/data

  app:
    build: .
    command: bundle exec rails s -p 3002 -b '0.0.0.0'
    volumes:
      - ".:/blog_app"
    ports:
      - "3002:3002"
    depends_on:
      - db
      - sidekiq
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: blog_app
      DB_PASSWORD: password
      DB_HOST: db

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    volumes:
      - .:/blog_app
    env_file:
      - .env

  # sidekiq:
  #   depends_on:
  #     - "db"
  #     - "redis"
  #   build:
  #     context: ..
  #     dockerfile: ./docker/Dockerfile
  #   command: sidekiq -C ./config/sidekiq.yml
  #   volumes:
  #       - "../.:/app"
  #   environment:
  #     REDIS_URL: redis://redis:6379
  #     DB_USERNAME: root
  #     DB_PASSWORD: root
  #     DB_PORT: 5432
  #     DB_HOST: db
  #     RAILS_ENV: development
  #     RAILS_MAX_THREADS: 5


volumes:
 db:
 redis: